version: '3.8'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=portfolio
    ports:
      - '3306:3306'
    volumes:
      - ./sql-init.sql:/docker-entrypoint-initdb.d/sql-init.sql